### ISSUE TITLE
ueditor.config.js

### ISSUE THREAD

**Issue by luocong2016** [ochukai/react-ueditor#2]
ueditor.config.js你这个文件都没有？

**Comment by ochukai** [comment]
ue 的所有代码都是在后端啊~ 你想看我可以发出来~

**Comment by ochukai** [comment]
根据自己的项目来配置的~

**Comment by luocong2016** [comment]
我这配置 只有蚂蚁那个一直转

**Comment by luocong2016** [comment]
@ochukai 能发整体项目？前端一个人配置好难。。。

我现在前端目录是 
src/components/Ueditor
>ueditor
>>createScript.js
>>Ueditor.js

**Comment by ochukai** [comment]
https://gist.github.com/ochukai/c95a63a4cf06a61912f303581b8e86af

**Comment by ochukai** [comment]
配置 ue 肯定要配置后端啊~ 你看看官方文档的实例就好了~

**Comment by luocong2016** [comment]
已经放弃了。百度要用jsp访问。我项目不能用。

**Comment by luocong2016** [comment]
网址不对
