### ISSUE TITLE
Is it BUG

### ISSUE THREAD

**Issue by luocong2016** [ochukai/react-ueditor#4]
webpack:///./~/fbjs/lib/warning.js?:36 Warning: List is changing an uncontrolled input of type undefined to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components
printWarning	@	webpack:///./~/fbjs/lib/warning.js?:36

**Comment by ochukai** [comment]
这是受控组件和非受控组件 你搞混了吗？
