### ISSUE TITLE
react组件卸载

### ISSUE THREAD

**Issue by baixiaosh** [ochukai/react-ueditor#5]
当这个组件被卸载的时候，加载的js能同时卸载吗？

**Comment by ochukai** [comment]
已经加载了的 js，就会一直存在浏览器了，但是像这种 ueditor ， 可能只暴漏 一个 Ueditor 这样的变量，置空可能就行。

你现在是遇到了什么问题吗，还是强迫症？

**Comment by baixiaosh** [comment]
强迫症吧，哈哈哈
